[2025-09-06 14:21:00] Created new data file.
[2025-09-06 14:21:00] Created default config file.
[2025-09-06 14:21:00] App started.
[2025-09-06 14:21:01] Unhandled exception:
Traceback (most recent call last):
  File "c:\Users\HP\OneDrive\Desktop\my automation projects\ExpenseTracker\expense_tracker_ready.py", line 352, in <module>
    app = ExpenseApp(root)
TypeError: ExpenseApp() takes no arguments

[2025-09-06 14:21:23] App started.
[2025-09-06 14:21:23] Unhandled exception:
Traceback (most recent call last):
  File "c:\Users\HP\OneDrive\Desktop\my automation projects\ExpenseTracker\expense_tracker_ready.py", line 352, in <module>
    app = ExpenseApp(root)
TypeError: ExpenseApp() takes no arguments

[2025-09-06 14:25:43] App started.
[2025-09-06 14:25:43] Unhandled exception:
Traceback (most recent call last):
  File "C:\Users\HP\OneDrive\Desktop\my automation projects\ExpenseTracker\expense_tracker_ready.py", line 352, in <module>
    app = ExpenseApp(root)
TypeError: ExpenseApp() takes no arguments

[2025-09-06 14:34:46] App started.
[2025-09-06 14:36:55] Added expense: 2025-09-06, Food, 100, pizza
[2025-09-06 14:39:59] App started.
[2025-09-06 14:41:16] App closed.
